# Generated by Django 3.0 on 2019-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionday',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
