# Generated by Django 3.0 on 2019-12-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_management_main', '0002_transactionday_profit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['text']},
        ),
    ]
